# Generated by Django 5.1.6 on 2025-02-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alumno', models.CharField(max_length=255, verbose_name='Nombre del alumno')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('nombre_padre', models.CharField(max_length=255, verbose_name='Nombre del padre')),
                ('nombre_madre', models.CharField(max_length=255, verbose_name='Nombre de la madre')),
                ('grado', models.CharField(max_length=50, verbose_name='Grado')),
                ('seccion', models.CharField(max_length=50, verbose_name='Sección')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
            ],
        ),
    ]
