version: '3.9'

services:
  # Contenedor Principal (Django) para archivos estaticos
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app/
      - ./app/static_volume/:/usr/src/app/static/
      - /app/media_volume:/usr/src/app/media/
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminPass123
      - POSTGRES_DB=pruebaPython

volumes:
  postgres_data:
  cache:
  static_volume:
  media_volume: